app = 'crypto-trading-bot-czaheg'
primary_region = 'sin'

[build]
  # Ensure builds use the correct region
  [build.regions]
    allowed = ["sin"]

[[services]]
  internal_port = 3000  # Match your app’s listening port
  protocol = "tcp"      # Required for WebSockets

  [services.concurrency]
    hard_limit = 50     # Adjust for your needs
    soft_limit = 25

  # Handle HTTP/HTTPS and WebSocket upgrades
  [[services.ports]]
    handlers = ["http"]
    port = 80           # Inbound HTTP (upgrades to WebSocket)
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443          # Inbound HTTPS (upgrades to WebSocket)

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000

  [[services.processes]]
    name = "app"
    cmd = "node index.js"

  [[services.http_checks]]
    interval = "10s"
    grace_period = "5s"
    method = "get"
    path = "/health"  # Make sure your app has this endpoint
    protocol = "http"
    timeout = "2s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[egress]]
  region = "sin"